services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data 
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx2048m 
    restart: always 
    networks:
      - nexus-net 

volumes:
  nexus-data:
    driver: local

networks:
  nexus-net: 
    driver: bridge