services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  
      - /root/DEVOPS:/srv  # Mount /root/DEVOPS to /srv inside the container
      - caddy_data:/data  
      - caddy_config:/config 
volumes:
  caddy_data:
  caddy_config:

