global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Scrape node-exporter from this service

