services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0  # Replace with the latest version if needed
    container_name: cadvisor
    ports:
      - "8080:8080"  # Cadvisor metrics port
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
